version: '2'
services:
  nextcloud:
    image: nextcloud
    restart: always
    networks:
      - docker
    ports:
      - 4888:80
    volumes:
      - "/mnt/docker/nextcloud:/var/www/html"
      - "/mnt/nextcloud/data:/var/www/html/data"
networks:
  docker:
    external: true
