version: '2'
services:
  ghost:
    image: ghost
    restart: always
    ports:
      - 2369:2368
    volumes:
      - "/mnt/docker/didi.style:/var/lib/ghost/content"
    environment:
      - "url=http://didi.style"