version: '2'
services:
  huginn:
    image: huginn/huginn
    restart: always
    networks:
      - docker
    ports:
      - "8083:3000"
    environment:
      - "DOMAIN=huginn.victorqhong.com"
      - "EMAIL_FROM_ADDRESS=notifications@victorqhong.com"
      - "INVITATION_CODE=nJ44%oSl57eW8P"
      - "PORT=3000"
      - "SMTP_AUTHENTICATION=login"
      - "SMTP_DOMAIN=victorqhong.com"
      - "SMTP_PASSWORD=8Ej6j556tN"
      - "SMTP_SERVER=mail.victorqhong.com"
      - "SMTP_USER_NAME=notifications@victorqhong.com"
      - "TIMEZONE='Eastern Time (US & Canada)'"
      - "DATABASE_HOST=mysql"
      - "DATABASE_NAME=huginn"
      - "DATABASE_USERNAME=huginn"
      - "DATABASE_PASSWORD=iC4Pw3RJrUQY"
      - "DATABASE_ENCODING=utf8mb4"
      - "DO_NOT_CREATE_DATABASE=true"
      - "DO_NOT_MIGRATE=true"
      - "DO_NOT_SEED=true"
      - "RAILS_ENV=production"
      - "START_MYSQL=false"
networks:
  docker:
    external: true
